name: practice_design_patterns_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  go_router: ^6.0.3
  flutter_riverpod: ^2.3.0

  # flutter_svg: ^1.0.3
  # kakao_flutter_sdk_user: ^1.4.1
  # flutter_dotenv: ^5.0.2
  # kakao_flutter_sdk: ^1.4.0
  # kakao_flutter_sdk_common: ^1.4.0
  # kakao_flutter_sdk_template: ^1.4.0
  # sign_in_with_apple: ^4.3.0
  # change_app_package_name: ^1.1.0
  # shared_preferences: ^2.0.17
  # flutter_secure_storage: ^8.0.0
  # dio: ^4.0.6
  # retrofit: ^3.3.1
  # intl: ^0.17.0
  # json_annotation: ^4.8.0
  # cached_network_image: ^3.2.3
  #skeletons: ^0.0.3

  # expandable: ^5.0.1
  # dotted_decoration: ^2.0.0
  fluttertoast: ^8.2.1
  # animated_text_kit: ^4.2.2
  # flutter_fadein: ^2.0.0
  # syncfusion_flutter_charts: ^20.4.50
  # flutter_localizations:
  #   sdk: flutter

  # syncfusion_flutter_gauges: ^20.4.50
  # package_info_plus: ^3.0.3
  # card_slider: ^1.0.5
  # carousel_slider: ^4.2.1
  # riverpod_annotation: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  # json_serializable: ^6.6.1
  # retrofit_generator: ^4.2.0
  # build_runner: ^2.3.3
  # riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true

  #
